---
language: python
services:
  - docker
env:
  global:
    - ROLE_NAME: hdp-ambari-agent
  matrix:
    - MOLECULE_DISTRO: centos:6
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: ubuntu:trusty
    - MOLECULE_DISTRO: ubuntu:xenial
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule docker
before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME rgibert.$ROLE_NAME
  - cd rgibert.$ROLE_NAME
script:
  - molecule test
