---
- block:

  - include_tasks: "repo-{{ ansible_os_family }}.yml"

  - name: install ambari-agent
    package:
      name: ambari-agent
      state: latest
    notify: restart ambari-agent
    tags:
      - install_ambari_agent

  - name: update ambari-agent config
    lineinfile:
      dest: /etc/ambari-agent/conf/ambari-agent.ini
      regexp: '{{ item.re }}'
      line: '{{ item.l }}'
    notify: restart ambari-agent
    with_items:
      - re: '^logdir=.*'
        l: 'logdir={{ ambari_agent_log_dir }}'
      - re: '^loglevel=.*'
        l: 'loglevel={{ ambari_agent_log_level }}'
      - re: '^run_as_user=.*'
        l: 'run_as_user={{ ambari_agent_user }}'
      - re: '^hostname=.*'
        l: 'hostname={{ ambari_server_host }}'
      - re: '^url_port=.*'
        l: 'url_port={{ ambari_server_port }}'
      - re: '^secured_url_port=.*'
        l: 'secured_url_port={{ ambari_server_secure_port }}'
    tags:
      - update_config

  - name: fix path permissions
    file:
      state: directory
      path: '{{ item.p }}'
      owner: '{{ ambari_agent_user }}'
      group: '{{ ambari_agent_group }}'
      mode: '{{ item.m }}'
    with_items:
      - p: /var/lib/ambari-agent/tmp
        m: '0777'
      - p: '{{ ambari_agent_log_dir }}'
        m: '0755'
    tags:
      - fix_path_perms

  - name: start and enable ambari-agent
    service:
      name: ambari-agent
      state: started
      enabled: yes
    tags:
      - start_ambari_agent
      - enable_ambari_agent

  tags:
    - ambari-agent
