---
- block:

  - include_tasks: "{{ ansible_os_family }}-repo.yml"
  - include_tasks: "{{ ansible_os_family }}-install.yml"

  - name: update ambari-agent config
    lineinfile:
      dest: /etc/ambari-agent/conf/ambari-agent.ini
      regexp: '{{ item.re }}'
      line: '{{ item.l }}'
    notify: restart ambari-agent
    with_items:
      - re: '^logdir=.*'
        l: 'logdir={{ ambari_agent_log_dir }}'
      - re: '^loglevel=.*'
        l: 'loglevel={{ ambari_agent_log_level }}'
      - re: '^run_as_user=.*'
        l: 'run_as_user={{ ambari_agent_user }}'
      - re: '^hostname=.*'
        l: 'hostname={{ ambari_server_host }}'
      - re: '^url_port=.*'
        l: 'url_port={{ ambari_server_port }}'
      - re: '^secured_url_port=.*'
        l: 'secured_url_port={{ ambari_server_secure_port }}'
    tags:
      - update_config

  - name: fix path permissions
    file:
      state: directory
      path: '{{ item.p }}'
      owner: '{{ ambari_agent_user }}'
      group: '{{ ambari_agent_group }}'
      mode: '{{ item.m }}'
      recurse: true
    with_items:
      - p: '/var/lib/ambari-agent/tmp'
        m: 'u=rwX,g=rwX,o=rwX'
      - p: '{{ ambari_agent_log_dir }}'
        m: 'u=rwX,g=rX,o=rX'
      - p: '/etc/ambari-agent/conf'
        m: 'u=rwX,g=rX,o=rX'
    tags:
      - fix_path_perms

  - name: start and enable ambari-agent
    service:
      name: ambari-agent
      state: started
      enabled: true
    tags:
      - start_ambari_agent
      - enable_ambari_agent

  tags:
    - ambari-agent
